### ISSUE TITLE
For OpenCV 3.2 or higher version usage

### ISSUE THREAD

**Issue by sngjuk** [njean42/kumiko#1]
kumikolib.py
change

`contours, hierarchy = cv.findContours(thresh, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)`

to 
`_ , contours, hierarchy = cv.findContours(thresh, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)`

[OpenCV docs](https://docs.opencv.org/3.4/d4/d73/tutorial_py_contours_begin.html)

**Comment by njean42** [comment]
Thanks for your comment sngjuk!
I haven't been able to check, are you sure this is the only opencv method that changes in Kumiko with version 3.2?

**Comment by sngjuk** [comment]
Yes, this is the only method that incompatible with 3.4.4 that I'm using. (Last released: Nov 28, 2018)
Thanks for sharing kumiko!

**Comment by sngjuk** [comment]
From 4.0.0, findContours() changed to return only the contours and the hierarchy and not ret..
https://docs.opencv.org/4.0.0/d4/d73/tutorial_py_contours_begin.html

**Comment by njean42** [comment]
Kumiko is now compatible with python 3 and opencv 4 (4.2.0)
