### ISSUE TITLE
Kumiko can't detect panels within a page with black background

### ISSUE THREAD

**Issue by raf555** [njean42/kumiko#10]
I tried the kumiko through the [online demo](https://kumiko.njean.me/demo). Some other pages with white background are working great, but then I tried this page with black color background and kumiko only detected it as a single panel. 

Perhaps you have solution for this? Thanks!

Image:

![Screenshot_20220729-191621](https://user-images.githubusercontent.com/8206338/181756557-cf28dceb-16c9-46e4-848f-1d2aab249fd0.jpg)

**Comment by njean42** [comment]
Hey @raf555 
Thanks for posting this issue. _Kumiko_ is supposed to try both bright and dark (white-ish and black-ish) background in panel detection. Probably there is something specific with the picture you posted that prevents proper processing.
I'll use it as an basis to debug :+1:. Cannot work on it right now, but hopefully I can check it out soon.

**Comment by njean42** [comment]
Pheeew, this brought many changes to the code.
Thanks to a sobel filter and quite some tweaks, _Kumiko_ is now able to detect panels on any background color! (`v1.5`)

Thanks again for reporting the issue, and let me know if you try out other images.
