### ISSUE TITLE
Ordering seems off in certain cases

### ISSUE THREAD

**Issue by antoinedelplace** [njean42/kumiko#12]
In the following image, the 6th panel is not right positionned.

Original page can be found here : https://i.pinimg.com/originals/22/d3/60/22d360573d335e84f85c7c734e94b8af.jpg

![image](https://github.com/njean42/kumiko/assets/34864698/3dc033f2-8e03-45e4-a803-ad824b3bc003)

**Comment by antoinedelplace** [comment]
It seems that those lines are not enough :
https://github.com/njean42/kumiko/blob/527cc42aed8c27d7cecd55acb64e419904084fd2/lib/panel.py#LL53C2-L70C12

It only relies on the position of the two panels to order, whereas the presence of a panel "in the middle" could change the order.
See an example below :
![image](https://github.com/njean42/kumiko/assets/34864698/45351067-ca27-4b1c-b3af-6b7d0e889de1)

**Comment by antoinedelplace** [comment]
This guy [here](https://maxhalford.github.io/blog/comic-book-panel-segmentation/) uses a smart recursive function to order the panels.
It alternates between row and column ordering recursively.
(cc @MaxHalford)

**Comment by MaxHalford** [comment]
Wow I'm so happy you pinged me, it's great to discover this project!

I do remember designing this recursive algorithm, exactly to solve the Tintin example you shared above. The idea is to group panels on the same row/column, and proceed recursively. Here's a rundown on the Tintin example you shared.

```
First, group panels into rows

R1 = P1 + P2 + P3 + P4
R2 = P5 + P7 + P8 + P9 + P10
R3 = P11 + P12

For each row, recurse and group panels into columns

R1.C1 = P1
R1.C2 = P2
R1.C3 = P3
R1.C4 = P4

R2.C1 = P5 + P7
R2.C2 = P8
R2.C3 = P9
R2.C4 = P6 + P11

R3.C1 = P11
R3.C2 = P12

Recursion can stop for groups of one panel.
There are only two groups with more than one panel.

R2.C1.R1 = P5
R2.C1.R2 = P7

R2.C4.R1 = P6
R2.C4.R2 = P11

Now label the panels according to the group key, i.e.

P1 = R1.C1 =  (1, 1)
P9 = R2.C3 = (2, 3)
P7 = R2.C1.R2 = (2, 1, 2)

You can now sort the panels according to these keys.
```

**Comment by antoinedelplace** [comment]
By the way @MaxHalford, for your algorithm to work properly, the panels need to be sorted at the beginning (and not at the end) of the clustering.

Here is a working python function :
```
def are_bboxes_aligned(xywh, other_xywh, axis, threshold=0.05):
    avg_length = (xywh[2 + axis]+other_xywh[2 + axis])/2

    a_min = xywh[0 + axis]
    a_max = xywh[0 + axis] + xywh[2 + axis]
    b_min = other_xywh[0 + axis]
    b_max = other_xywh[0 + axis] + other_xywh[2 + axis]

    return (
        a_min < b_max - threshold*avg_length and
        b_min < a_max - threshold*avg_length
    )

def cluster_panels(panels_xywh, axis=0):
    panels_xywh.sort(key=lambda c: c[0 + axis])

    clusters = []

    for bbox in panels_xywh:
        for cluster in clusters:
            if any(
                are_bboxes_aligned(other_bbox, bbox, axis=axis)
                for other_bbox in cluster
            ):
                cluster.append(bbox)
                break
        else:
            clusters.append([bbox])

    for i_cluster, cluster in enumerate(clusters):
        if len(cluster) > 1:
            clusters[i_cluster] = cluster_panels(
                panels_xywh=cluster,
                axis=1 if axis == 0 else 0
            )

    return clusters
```

**Comment by njean42** [comment]
Hey @antoinedelplace
Thank you very much for providing this example!

I've finally got down to working on _Kumiko_ a bit, and came up with [a patch](https://github.com/njean42/kumiko/commit/e6a5fe13b79bf59f622616fb20a8466e9b8001bd#diff-1b1c9bec184f82d81b33b9b0f3a316c4e4a8d441d5d9652a97aeeeffe2b5cc0dR359-R375) to fix this numbering issue.

It does not work exactly with the _clusters_ approach you mentioned, but something similar.

Now each panel checks whether it has neighbours − above, or on its left (= on the same row = in the same _cluster_) and whether their panel 'number' is greater than these panels' number.
If it isn't, the panel re-orders itself after it's left or top panel.

The result is pretty good! [diff for v1.4.2](https://kumiko.njean.me/tests/results/diff-v1.4.1-v1.4.2.html)
