### ISSUE TITLE
Extract image files of panels

### ISSUE THREAD

**Issue by plaidpants** [njean42/kumiko#13]
Would be a nice feature if you could extract png's or jpg's of the individual panels for additional processing such as image to text.

**Comment by Kaito0** [comment]
+1

**Comment by plaidpants** [comment]
I found this tool that seems to do a good job automatically splitting panels.
https://github.com/thieupepijn/ComicPanelSplitter

**Comment by njean42** [comment]
Good idea!
It seems like others have thought about this too. :slightly_smiling_face: 

@bouiboui, would you like to contribute by opening a PR with [your code](https://github.com/bouiboui/kumiko/commit/16a19b3556cf225751108ae3276a3e1c8e4fcf23?diff=split&w=1) to save panels into image files?

The code has changed a lot with version `v1.5`, but you should be able to merge your code into it with little effort.

(I've written a very short [contributing section here](https://github.com/njean42/kumiko#contributing).)

**Comment by plaidpants** [comment]
[diff.patch](https://github.com/njean42/kumiko/files/13851744/diff.patch)
Here is my probably terrible attempt at merging @bouiboui code with the current code, I also removed expand_panels so the saved panels would be the right size. It works well enough for my purposes but probably not good enough for others.

**Comment by njean42** [comment]
> my attempt at merging @bouiboui code with the current code

I'm not sure how to apply that patch (tried `patch`, `git apply`, `git am`…), could you help me with that?

> I also removed expand_panels so the saved panels would be the right size

We can add an option to prevent expanding panels. :blush: 

> It works well enough for my purposes but probably not good enough for others.

Let's start with the code you provided, and see if others then have ideas for improvement!

**Comment by plaidpants** [comment]
You should be able to apply the patch to the directory of the source code using when located in the directory.

A:\> patch -p0 < PatchFile

the original one above was created using beyond compare which I believe uses this sort of command under the hood

A:\> diff -ruN A:\kumiko-master-latest A:\kumiko-master-merge > diff.patch

I've attached another patch file that uses this command above, see if that works any better.

[diff.patch](https://github.com/njean42/kumiko/files/13896170/diff.patch)

**Comment by njean42** [comment]
> I've attached another patch file that uses this command above, see if that works any better.

Very much!
Cool, I've created a branch and PR for this, i'll try out the code and maybe make a few changes.

#15

**Comment by njean42** [comment]
Hi all,
I've pretty much finished integrating this feature.

Please try it out (on branch `13-extract-image-files-of-panels`) and tell me what you think, if something's missing, etc.

You're also welcome to comment on [the code](https://github.com/njean42/kumiko/pull/15/files).

**Comment by bouiboui** [comment]
I apologize for the delay in responding; I took a break from coding due to the birth of my second son. :) 
Can I help, or were you able to resolve everything on your own?

**Comment by plaidpants** [comment]
the branch seems to work as well as what I had used previously, would be nice to be able to specify an output directory or use the current directory and create an output folder like the original branch as grabbing everything out of the temp directory is kind of a pain. Also, I didn't see a way to switch the border expansion off.

**Comment by njean42** [comment]
> would be nice to be able to specify an output directory

True, I'll add that! :slightly_smiling_face: 

> a way to switch the border expansion off

Ah yes, we're missing that still, I'll add it.
@bouiboui @plaidpants would you be so kind as to provide an example image where panel expansion is not desirable?

**Comment by njean42** [comment]
> birth of my second son. :)

Congrats :confetti_ball: 

> Can I help, or were you able to resolve everything on your own?

I integrated your code in this PR, made a few edits.
Mainly moving the panel saving feature to `kumikolib.py`, so it's able to do it even if not called from the command-line (e.g. from a website version of _Kumiko_, a bit like the demo).

You're welcome to comment on the code or suggest code changes, but no hard push. :grin:

**Comment by njean42** [comment]
> would be nice to be able to specify an output directory
> a way to switch the border expansion off

Both options are now available :slightly_smiling_face:

**Comment by bouiboui** [comment]
> > birth of my second son. :)
> 
> Congrats 🎊
> 
> > Can I help, or were you able to resolve everything on your own?
> 
> I integrated your code in this PR, made a few edits. Mainly moving the panel saving feature to `kumikolib.py`, so it's able to do it even if not called from the command-line (e.g. from a website version of _Kumiko_, a bit like the demo).
> 
> You're welcome to comment on the code or suggest code changes, but no hard push. 😁

I'm sorry I didn't code more carefully, I bulldozered my way in to make my use case work, congratulations for sorting it out!

I'll take a second look at your code but I'm not in a very good position to judge, I'm self-taught in Python and still trying to figure things out most of the time.

**Comment by njean42** [comment]
> I'm sorry I didn't code more carefully, I bulldozered my way in to make my use case work, congratulations for sorting it out!

Don't even worry, if anything, it was a very good hint for me to integrate panels saving into _Kumiko_!

> I'll take a second look at your code but I'm not in a very good position to judge, I'm self-taught in Python and still trying to figure things out most of the time.

Any comment is welcome; none is of course fully okay as well.
