### ISSUE TITLE
Can't figure out how to use kumiko

### ISSUE THREAD

**Issue by GutUser3** [njean42/kumiko#14]
I am terribly sorry if I am simply misunderstanding something, but I can't seem to launch/use kumiko in command line at all. I open command line in the folder with kumiko in it, but any command, like kumiko --help, only produces:
"'kumiko' is not recognized as an internal or external command, operable program or batch file."
I've tried on Windows and in WSL, but the issue is the same. I am probably missing something fundamental, seeing as it works on many machines. I would appreciate any help

**Comment by njean42** [comment]
Hi @GutUser3,
I would be surprised if _kumiko_ was already working on Windows, given that I haven't tested it there at all.

That being said, the error you mention looks very much like your `$PATH` doesn't include the _kumiko_ script location, so the command line doesn't know where to find it.

A common way to have it working is to provide the relative or absolute path to the script, on Linux this would look like:
```bash
./kumiko --help
```
or
```bash
/path/to/kumiko --help
```
