### ISSUE TITLE
Run kumiko from python script for local files

### ISSUE THREAD

**Issue by SmallThings-coder** [njean42/kumiko#18]
Hello. I'm trying to execute Kumiko in the Python script on some saved manga images stored on my PC. I tried to follow one of the previous issues by downloading lib folder and kumikolib and running:
`from kumikolib import Kumiko
k= Kumiko()
info = k.parse_url_list(["path to the image"])
panels = info[0]['panels']`

but `info` turned out to be` None`.
What am I doing wrong? Is there even a way to run Kumiko like this?

**Comment by njean42** [comment]
Hi there.
That one method you're using, `parse_url_list`, will assume you're passing it URLs, and try to download images locally before processing them.
Since you already have your image locally, you can use `parse_image` instead:

```python
from kumikolib import Kumiko

k= Kumiko()
k.parse_image("/path/to/image")
panels = k.get_infos()[0]['panels']
print(panels)
```

**Comment by SmallThings-coder** [comment]
Thank you, it worked!
