### ISSUE TITLE
ZeroDivisionError 

### ISSUE THREAD

**Issue by cosmokaygc** [njean42/kumiko#19]
Kumiko throws a ZeroDivisionError when running the algorithm on this image as input. Resolution matters when creating this bug, so this image may not throw an error because of the compression while uploading it. If that's the case  I can work with you to get the image to you at the correct resolution.

![189_fb517284c29c2a3aef0699a1ad2c6db8](https://github.com/njean42/kumiko/assets/152348048/1f7d18a1-19b3-43a6-bd72-c927675e1b0e)

Here is an image of the error logging in the terminal. I've spent some time poking around, but didn't really get anywhere as I don't know python too well.

<img width="617" alt="image" src="https://github.com/njean42/kumiko/assets/152348048/3d9daca8-439d-437f-b22a-9bc5fe38d169">

**Comment by louxiu** [comment]
I encounter similar problem and craft a PR(https://github.com/njean42/kumiko/pull/20).

**Comment by njean42** [comment]
Thank you both for reporting the issue and providing a fix!

**Comment by njean42** [comment]
Closing this after merging @louxiu's PR
