### ISSUE TITLE
Excellent!

### ISSUE THREAD

**Issue by crouti** [njean42/kumiko#2]
I would like to use your excellent tool to create on online comic library based on your demo front end (extending it of course).
Is this code also shared ?
Thanks a lot!

**Comment by crouti** [comment]
Oh sorry, i see this code available as well.
Keep up the good work!

**Comment by njean42** [comment]
Hi @crouti 
and thanks for your comment!

The _reader_ and _reader-gui_ JS files are published indeed.

If you mean the server code behind [the demo](https://kumiko-demo.njean.me/), I don't think it shared for now.
It mainly consists of checking the image URLs sent by visitors, and passing them to the _kumiko_ lib for analysis (all in php).

Let me know if you come up with a great use for _Kumiko_ :)

Cheers

**Comment by crouti** [comment]
Thanks for your answer, i actually make the server side myself because i want to add the sound feature for my children : be able to record my voice reading a comic and play it simultaneously while the frame is displayed.
I ll start with your js and make some more.
Any remark or advice welcome!!!
Cheers!

**Comment by crouti** [comment]
I imported both you css and your js (just a little tweak), but it seems there is a problem on frame resizing....
https://www.ilurn.com/comic_books/le-secret-de-la-licorne/

Any idea ?

**Comment by crouti** [comment]
Solved, it was CSS conflict on #container, changed the name to #comic-container, and all works.
Thanks !

**Comment by njean42** [comment]
Oh yeah, the class naming isn't very specific, thus not very portable.
_Kumiko_ seems to work great with that first page of Tintin's _The Secret of the Unicorn_.

Note that you should be able to have as many comics pages as you want in one container, i.e. one web page (you may want to cache the results on the server-side).
That way you can click next and it will bring you from panel to panel, but also switch page to go from the last panel of page _x_ to the first of page _x+1_ (and back).

Very nice idea to add audio to it, guess your kids will love it!
