### ISSUE TITLE
Python rather than command line

### ISSUE THREAD

**Issue by kevinlinxc** [njean42/kumiko#6]
Hello, I was wondering how I could use kumiko in a python script rather than from the command line.

**Comment by kevinlinxc** [comment]
Figured it out:

**Comment by kevinlinxc** [comment]
Figured it out:

Download panel.py and kumikolib.py

from kumikolib import Kumiko
k= Kumiko()
info = k.parse_url_list(["comicimagelink"])
panels = info[0]['panels']

**Comment by njean42** [comment]
Exactly, that's basically what the main script does (`kumiko` file).

You can check how the various command-line parameters are handled there, to find out how to pass information that fits your need to the Kumiko class. ;)
