### ISSUE TITLE
Parameter tuning

### ISSUE THREAD

**Issue by kevinlinxc** [njean42/kumiko#7]
I notice that when cutting certain xkcd comics, the cutting is not perfect, which is expected for a general-purpose tool. For example, [This xkcd](https://imgs.xkcd.com/comics/e_to_the_pi_minus_pi.png) creates a panel that starts at the left edge and goes halfway into the second panel  
[as so](https://user-images.githubusercontent.com/44324811/114436932-c8ac9100-9b7a-11eb-8cba-16bc22ac8e50.png). Which parameters should I tune in order to avoid these? Contour detection? panel.split?

[Another example](https://imgs.xkcd.com/comics/placebo_blocker.png) finds this 
[this](https://user-images.githubusercontent.com/44324811/114439482-e2030c80-9b7d-11eb-9048-bf4f789aaf3c.png) as a panel

**Comment by njean42** [comment]
You're completely right.

Currently _Kumiko_ can only detect panels that are surrounded by a frame. Both examples - and numerous other *xkcd*s - have one of those panels with no boundary.
In classical/colourful comics, this is mitigated by each panel having some background color(s) that serves as boundary (in the contour detection _Kumiko_ performs).

But in _xkcd_, non-framed panels suffer very erratic detection: many small bits of the inner drawing get detected as panels. Then Kumiko tries to expand those panels (and the left one you mention), making the situation even worse (=> the left panel goes half-way through the second one).
You can actually see the detected panels on [the demo](https://kumiko.njean.me/demo) I just relaunched (after computation, type `p` to view full page then `d` for debug - those shortcuts are listed in the menu, type `m` :smile:)

This is something I want to address, probably by grouping smaller panels and checking if they can make a larger one, when merged together.

**Comment by kevinlinxc** [comment]
I added a 1 pixel padding to the comic (cv2.copyMakeBorder) and it seems to be working better: 
![image](https://user-images.githubusercontent.com/44324811/114457594-103f1700-9b93-11eb-8209-ae57259129e3.png)

This could be an option for Kumiko, if you remove the padding after, but it's kind of hacky so maybe not. Thanks for your help, the demo makes verification of this method way easier.

**Comment by njean42** [comment]
Happy to hear that the demo proves useful! :v: 
Interesting, it crossed my mind that the absence of padding could be an issue, but really thought it was something else in this case.
It is a bit hacky but definitely an option to explore.

**Comment by njean42** [comment]
Hi back @kevinlinxc 
So I coded this "_grouping of small panels_", to detect text and drawings outside of frames; just pushed it.
The demo is also updated, you can check that it now works much better for _xkcds_! (although not perfectly for some)
I tried the last dozen of them :wink: 
(Edit 1: I didn't yet take the 1px-margin approach)
(Edit 2: The second example you provided still has a major issue though, it seems - will work on it as an example)
