### ISSUE TITLE
kumiko takes a couple of minutes to process some pages

### ISSUE THREAD

**Issue by Kamikadashi** [njean42/kumiko#8]
Hi! Sometimes when the image is too big and sharp kumiko takes more than a minute to process a single page (instead of a second). Apparently this can be fixed with applying GaussianBlur or resizing the page in question. For example, by adding a line to the kumikolib.py file:
```diff
	def parse_image(self,filename,url=None):
		self.img = cv.imread(filename)
+		self.img = cv.GaussianBlur(self.img,(5,5),0)
```
The solution is from [here](https://github.com/xulihang/ImageTrans-docs/issues/147#issuecomment-1031017867)

**Comment by njean42** [comment]
Hey @Kamikadashi,
Thank you very much for posting this report here!

The `GaussianBlur` solution did solve the speed issue, but broke panel detection in numerous images (you can add the line and run `./tester.py -b firefox` to see broken examples). Basically, sometimes it blurs panels edges together, so those panels are not detected as distinct from each other any more.

I added optimised the small panels grouping, which was responsible for Kumiko's slowness in the case of _sharp_ images.

Can you run Kumiko `v1.4.1` on offending images, and share your experience here?
Also @nnuel :wink: 

Thanks!

**Comment by mspykerez** [comment]
Thx for keeping this project alive!
If you wish to join more comic/manga fans on making the best tools for reading/translating them I say to join the [Sugoi Japanese Translator](https://www.reddit.com/r/visualnovels/comments/rzhbdz/from_sugoi_translator_developer_i_present_you_the/) discord https://discord.com/invite/XFbWSjMHJh where many developers from different projects relating to games and manga are congregating.
