### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by nnuel** [njean42/kumiko#9]
I'd really like to test out the software, but `pip install kumiko` doesn't work on my end. 

```
ERROR: Could not find a version that satisfies the requirement kumiko
ERROR: No matching distribution found for kumiko
```

What could I do to make this work and can kumiko deal with .cbz/cbr files?

**Comment by rachmadaniHaryono** [comment]
kumiko is not yet on pypi

you have to clone the repo, install the required package (opencv, numpy and requests) with pip and run kumiko

i tried to make this pip installable on my repo, so you can also try that

if you use pipx

`pipx install https://github.com/rachmadaniHaryono/kumiko/archive/refs/heads/master.zip`

you can also install with pip but i recommend to install it on virtualenv or use pipx as mentioned above

after that you have `kumiko` command and can check help section with `kumiko --help`

e: 

> kumiko deal with .cbz/cbr files?

kumiko don't work with archive yet, so you have to extract it

**Comment by njean42** [comment]
Thanks @rachmadaniHaryono for the reply, `git clone` + install dependencies is indeed the way to go.

@nnuel please share the results of your running kumiko on your comics :slightly_smiling_face:  (Kumiko can work on a directory with multiple image files, which I believe is what you get when extracting a `cbz/r` file.)

**Comment by nnuel** [comment]
Yes, I forgot to use `./kumiko` the first time I cloned into the repository. Also had to install the python version of opencv instead of the normal opencv. But then it works. I can get it to open the browser on a single image, but with the 24 images of this comic book in the acbf format: http://acbf.info/show_book.html?id=0002, then takes a long time to run the python command. How long should it take to go through 24 images like that?

I cut it off after 140s of 100% CPU power. Will attempt later again, guess it's a problem on my end.

**Comment by rachmadaniHaryono** [comment]
maybe related to #8

**Comment by njean42** [comment]
Kumiko is slow on big images.
I still have to try out @rachmadaniHaryono's proposed solution in #8; will followup there :wink: 

In the meantime, you can try to batch-shrink your comics pages, so that you can have a result in a reasonable time.
